### ISSUE TITLE
[Bug]: Right margin line numbers not working anymore

### ISSUE THREAD

**Issue by Phlosioneer** [Turing-Complete-Game/Suggestions-and-Issues#132]
### What happened?

Since I played yesterday, line numbers in the right margin now include non-code statements like comments, `const`, and `label`. The debugger pauses on those lines, instead of the line being executed; and when it's pointing at a valid line of assembly, it really means a different line is currently executing.

![20211126162027_1](https://user-images.githubusercontent.com/4657718/143655804-b06c31d3-6f0f-4b10-8885-ce45738ed64c.jpg)
 

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tali713** [comment]
Similar issue here on 0.338; should also note that this affects alignment checking which may cause programs to fail erroneously.  Turning off alignment checking is a temporary solution.

**Comment by Tabiskabis** [comment]
![alignment fail](https://user-images.githubusercontent.com/23276816/143701051-a8f43416-de4d-4b8d-b7fd-63588ece0c98.png)

Instruction counter/highlighting don't match the actual lines anymore. Apparently caused by not ignoring label lines, like comments.  
v0.339

Though probably related, this bug is probably worse than the changed font issue, since it's not as obvious to see what's wrong.

**Comment by Stuffe** [comment]
this was a bug in the new assembler, it forgot to take comment lines into account when calculating byte offsets but its fixed now
