### ISSUE TITLE
[bug]: broken factory component

### ISSUE THREAD

**Issue by DEPREZR** [Turing-Complete-Game/Suggestions-and-Issues#133]
### What happened?

One of my factory component (leg architecture calculation) is strangely broken.
Each time I load the divide level, first test fail. Checking detail : it seems to be my sub instruction which fail. Component receive good inputs (inst + 2 arguments) but output badly 0. But if I look at my calculation component inside factory (changing nothing), then go back to level, it works great again, and I can pass all tests I want without any issue.
I can reproduce the issue each time I restart the game ( and so if you want I can share you my savefile, just tell me how to proceed) 

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
I know that this was an issue for some time, but I believe this has been fixed in the most recent versions. What version are you on? (look in main menu, most recent should be 0.339 beta).

If it is still an issue in that version, upload your save to https://turingcomplete.game/report_bug and mention this issue's number

**Comment by DEPREZR** [comment]
I’m on the version you mentionned and I dont reproduce anymore. Last try reproducing issue was yesterday and I didnt played since. Honestly I dont see each time steam update the game, I let it do automatically. But it seems to be okay on last version :)

**Comment by MegaIng** [comment]
Then I believe that this has been fixed.
