### ISSUE TITLE
[Request]: More flexibility in the Program components

### ISSUE THREAD

**Issue by atsjewell** [Turing-Complete-Game/Suggestions-and-Issues#152]
### Request?

What I would really like to see is a Program component that emits the 1 to 4 bytes per tick but ALSO has the larger 64 Bit counter to address it. Also I would like to be able to define 16 Bit instructions in the assembler.

One byte is far too small to adequately address the four smaller "byte" output program components. You can't do anything "fun" with this except the most trivial.  Granted, I get that it may not have been the vision for this to be a general purpose simulator for anything of significant scale.. but that's like giving a creative kid a pile of LEGO and then telling him you didn't imagine he'd use it to build a scale replica of the USS Enterprise with working catapults.  We've got us some powerful LEGO here.

The only Program component that accepts the 64 Bit address also emits only 64 Bit instructions.  But that is insanely large for a single instruction.  Even IRL, 64 Bit computers may have 64 Bit Registers and Data Buses, etc.. but the instructions themselves are still usually 16 Bits with multiple reads from program memory used to build up to 64 bit operands when they're needed.  But we can't even do that with the 64 bit program component, because the tool to define new assembler instructions is itself limited to 8 bits.  To be clear, 8 bits is plenty as long as there is way to position those 8 bits around within the 64 bit space.  However, there does not seem to be a way to do that, so we're limited to accessing only the lowest 8 of the 64 bits with the assembler.  Even if we could use a "space" to demarcate bytes within the 64 bits instruction line, that would be a huge improvement. Technically, it's doing that already in the 2,3 and 4 output byte program components, so it wouldn't be a huge leap to have it behave the same way with the 64 bit program component.

Ideally though.. we REALLY need a Program Component with a 64 bit address space and that emits 16 bits "words" with the ability to define instructions with all 16 bits. 

Using the Motorola 68K as an example (but the Intel x86 is somewhat similar) instructions are 16 bits. The 4 MSBs define the actual instruction, with 0000 and 1111 being special cases for immediate mode and other specialized instructions.  The two non-immediate operands are each defined in 6 bits: 3 to select from 1 of 8 registers and 3 to select the addressing mode with 000 being Data Direct that use the 8 "Data Registers" and the remaining modes making use of the 8 "Address Registers" (16 registers total).  That's a lot of functionality packed into 16 bits.  There are instructions that can operate with 64 Bit "Quads", but even in those cases the Quad is built up from multiple 16 bit extensions.  My point is.. 64 bits is WAY too much for a single instruction. 8 Bits is too small (but can be made to work with the aforementioned changes). 16 would be ideal though.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
There are different things you are mentioning:


> Only 8bit assembly codes can be defined

Yes, this is a limitation that should be fixed at some point.

> 64bit is to large

This is intentional: Nothing is preventing you from just using the lower bits of such a wire. It prevents the game from favoring 16, 24, 32 or whatever bit. Also, 64bit = 8bit * 8, so it's a natural next step for builtin components.

64bit being to large for a single instruction is your opinion: I personally did design an architecture that makes full use of the 64bit.

> 8 bits is plenty as long as there is way to position those 8 bits around within the 64 bit space. However, there does not seem to be a way to do that

While not the most convenient, it is currently possible to kinda do this via the binary operators, especially `*`, e.g. `a*65536` to shift over the instruction two bytes. In this regard supporting shift operators would be decent bandage. 

> Program Component with a 64 bit address space and that emits 16 bits "words" 

This would require some magic memory mapping. That is something that you could implement yourself for your CPU :-)

You can already do something like supporting 16bit words in a 18bit program space by taking the lower two bits of the program counter and selecting part of the 64bit output instead of feeding them into the address port directly


I also believe it is unlikely that you will be writing programs that make full use of the 16bit address space by hand in the ingame editor, so you will probably be using some kind of external assembler, which you can tell to combine 4 16bit instructions. Soon there will also be a component that allows you to access the file system directly, making use of an external assembler easier.

**Comment by atsjewell** [comment]
All good points, and I'm looking forward to the external assembler.

> You can already do something like supporting 16bit words in a 18bit program space by taking the lower two bits of the program counter and selecting part of the 64bit output instead of feeding them into the address port directly

Genius.  :)

You didn't address the 'space' as a byte tokenize though.  I am very hopeful that this means you might be mulling this over more..  Consider this: Does anyone really intend to put two 64-bit instructions on the same line of the assembly editor? 

Using 'space' to tokenize bytes give us the ability to directly access the full 64 bits using the current 8 bit assembly codes without an awkward multiplication trick.  It "could" work Little Endian, but Big Endian would be better so that the internal representation matches what we see.

This, combined with your suggestion of using the lower 2 bits of the counter as offset into the current 64bit instruction, and we're off to the races.  

The only thing that would remain to resolve is how to define integer constants within the 64 bits. One option is to add suffixes B,W,L,Q (Byte, Word, Long, Quad for 1, 2, 4 and 8 bytes respectively).  Eg. 60984L would occupy the next 4 bytes.  Another option is to add support for Hexadecimal then we can literally spell out the number of bytes we intend to use: 0x0000EE38. 

Thank you for any consideration you give this.

**Comment by SunCatMC** [comment]
> add support for Hexadecimal

I just wrote 0xFFFFFFFF in a 64 bit program component, and it seems to work fine

**Comment by Stuffe** [comment]
The 64 bit program component should address most of this (just ignore unused bytes and you wont need more than 16 bits address space for programming, a file component is coming for other usages.)

I will add an option for assembly instructions of different sizes at some point as you ask for, but I am closing this request as there is too much text and I will not forget this feature anyway. Cheers
