### ISSUE TITLE
A list of levels with cheated solutions on the leaderboard

### ISSUE THREAD

**Issue by MegaIng** [Turing-Complete-Game/Suggestions-and-Issues#171]
This is a list of levels where I believe there are cheated solutions on the leader board. I will list all levels in the game and check boxes those were I believe there are no cheated solutions (at the top at least)

Note that this includes both obsolete scores and test-case-abuse scores.

Many of the architectures in the below list have the problem of some of the top scores using the old tick count, therefore having one tick advantage. If that is the only thing I am not going to add a comment.

- [x] [NOT Gate](https://turingcomplete.live/#not_gate)
- [x] [NOR Gate](https://turingcomplete.live/#nor_gate)
- [x] [OR Gate](https://turingcomplete.live/#or_gate)
- [x] [AND Gate](https://turingcomplete.live/#and_gate)
- [x] [Second Tick](https://turingcomplete.live/#second_tick)
- [x] [XOR Gate](https://turingcomplete.live/#xor_gate)
- [x] [Bigger OR Gate](https://turingcomplete.live/#or_gate_3)
- [x] [Bigger AND Gate](https://turingcomplete.live/#and_gate_3)
- [x] [XNOR Gate](https://turingcomplete.live/#xnor)
- [x] [ODD Number of Signals](https://turingcomplete.live/#odd_number_of_signals)
- [x] [Double Trouble](https://turingcomplete.live/#any_doubles)
- [x] [Counting Signals](https://turingcomplete.live/#counting_signals)
- [x] [Byte OR](https://turingcomplete.live/#byte_or)
- [x] [Byte NOT](https://turingcomplete.live/#byte_not)
- [x] [Half Adder](https://turingcomplete.live/#bit_adder)
- [x] [Full Adder](https://turingcomplete.live/#full_adder)
- [ ] [Adding Bytes](https://turingcomplete.live/#byte_adder) (mine is valid, not sure about top three)
- [x] [Switch](https://turingcomplete.live/#byte_switch)
- [x] [Saving Gracefully](https://turingcomplete.live/#saving_gracefully)
- [x] [Bit Inverter](https://turingcomplete.live/#bit_inverter)
- [x] [Input Selector](https://turingcomplete.live/#byte_mux)
- [ ] [Saving Bytes](https://turingcomplete.live/#saving_bytes)
- [ ] [Counter](https://turingcomplete.live/#tick_tock) Not sure, top two might not be valid
- [x] [1 bit decoder](https://turingcomplete.live/#demux)
- [ ] [Signed negator](https://turingcomplete.live/#signed_negator) #166 
- [x] [3 bit decoder](https://turingcomplete.live/#demux_3)
- [ ] [Little Box](https://turingcomplete.live/#ram_component) top three *probably* cheated and/or obsolete
- [x] [One Way](https://turingcomplete.live/#buffer)
- [x] [Logic Engine](https://turingcomplete.live/#alu_1)
- [ ] [Arithmetic Engine](https://turingcomplete.live/#alu_2) I don't know what, if anything, is cheated
- [x] [Instruction Decoder](https://turingcomplete.live/#decoder)
- [x] [Conditions](https://turingcomplete.live/#conditions)
- [ ] [Add 5](https://turingcomplete.live/#binary_programming)
- [ ] [Calibrating Laser Cannons](https://turingcomplete.live/#circumference) 0/0/0 is for sure not valid for this level
- [ ] [Masking Time](https://turingcomplete.live/#mod_4)
- [ ] [Storage cracker](https://turingcomplete.live/#binary_search)
- [x] [The Maze](https://turingcomplete.live/#maze) (kind of. first two places are there because only first maze is scored)
- [x] [Byte Constant](https://turingcomplete.live/#byte_constant)
- [ ] [Byte AND](https://turingcomplete.live/#byte_and) test case abuse
- [ ] [XOR](https://turingcomplete.live/#compute_xor)
- [x] [Byte XOR](https://turingcomplete.live/#byte_xor)
- [ ] [Equality](https://turingcomplete.live/#byte_equal) Everything below 17/6 should be cheated, but not sure
- [ ] [Unsigned Less](https://turingcomplete.live/#byte_less) Small amount of test case abuse #176 
- [ ] [Signed Less](https://turingcomplete.live/#byte_less_i) Same as above
- [x] [RAM](https://turingcomplete.live/#ram)
- [ ] [Shift](https://turingcomplete.live/#shift) not sure if first place is a valid solution, but the list also contains many with one tick missing
- [ ] [The Product of Nibbles](https://turingcomplete.live/#multiply) #158 
- [ ] [Divide](https://turingcomplete.live/#divide) #159 
- [ ] [Planet Names](https://turingcomplete.live/#capitalize)
- [ ] [Delicious Order](https://turingcomplete.live/#sorter) (~~top three~~ or so should be valid, others might rely on zero not occurring)
- [ ] [Stack](https://turingcomplete.live/#stack) #160
- [ ] [Dancing Machine](https://turingcomplete.live/#dance) (top two should be valid, others maybe not)
- [x] [Tower of Radioactive Alloy](https://turingcomplete.live/#tower) (not sure about this one)
- [x] [Robot Racing](https://turingcomplete.live/#robot_racing) (not sure about this one)
- [ ] [AI Showdown](https://turingcomplete.live/#ai_showdown) first place is obsolete, using patched test case abuse, second place is missing a tick
- [x] [Water World](https://turingcomplete.live/#flood_predictor)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EnderShadow** [comment]
> Process finished with exit code 0

**Comment by altrag** [comment]
My Delicious order score is not valid (currently 2nd place) - it relies on zero to mark end of stream.  My best with the proper counter build is 300/34 at the moment.

**Comment by altrag** [comment]
My tower score is valid (79/14/61).

**Comment by MegaIng** [comment]
> My tower score is valid (79/14/61).

Even with the changed tick count? 61 seems to low.

**Comment by altrag** [comment]
My robot racing score is valid (63/10/63).

**Comment by scottanderson** [comment]
Currently, 75 players have received credit for beating the `level_map`, which has no level name in the API
https://turingcomplete.live/#level_map

**Comment by danielrab** [comment]
My solution for Arithmetic Engine is valid and is currently 1st place

**Comment by bmerry** [comment]
What do you consider cheating? Is 0/0 for an OR gate cheating or just the nature of the game? If that's cheating then probably almost every level has cheating.

**Comment by MegaIng** [comment]
@bmerry 

0/0 is 100% indented. Cheating is a hard to define term in this game, yes. In general cheating is "Solutions that don't follow the description as close as possible in the game" Note that this of course fails because some descriptions are not that clear. In general such levels should also be listed here.

**Comment by bmerry** [comment]
> @bmerry
> 
> 0/0 is 100% indented. Cheating is a hard to define term in this game, yes. In general cheating is "Solutions that don't follow the description as close as possible in the game" Note that this of course fails because some descriptions are not that clear. In general such levels should also be listed here.

Thanks. I can say that my 6/4 solution to Full Adder (added today and an improvement on the previous best) is legitimate then.

Are the delay-6 solutions to Saving Bytes valid? It seems like you need 2 for the SR latch itself, 2 for masking the output to handle the load enable, leaving only 2 for setting the SR pins, which isn't enough. But there are a few times I've been convinced something is impossible then found a solution :-)

**Comment by MegaIng** [comment]
We are pretty sure that the /6 solutions for saving bytes are not valid. That level should not be marked off, you are correct.

**Comment by scottanderson** [comment]
> Thanks. I can say that my 6/4 solution to Full Adder (added today and an improvement on the previous best) is legitimate then.

@bmerry please consider joining the TC Discord, I would love to ask you about this.

**Comment by tali713** [comment]
> My Delicious order score is not valid (currently 2nd place) - it relies on zero to mark end of stream. My best with the proper counter build is 300/34 at the moment.

even if you think you are using zero to mark end of stream you may in fact be using run-length to mark end of stream and simply writing early zeros before the rest of the stream is processed, which is still correct for fixed length lists.  (I'd have to see implementation to be certain).

**Comment by bmerry** [comment]
> @bmerry please consider joining the TC Discord, I would love to ask you about this.

@scottanderson can do. Where do I find the invitation link?

**Comment by bmerry** [comment]
> We are pretty sure that the /6 solutions for saving bytes are not valid. That level should not be marked off, you are correct.

What about 41/8? I can see that /8 is possible. However, per bit you'll need at least one nand on the output path (to apply the load disable) and two for the S/R itself, leaving only 2 nands per bit to compute the S/R inputs. My brute force solver indicates that one can't compute the S/R inputs with 2 nands in less than 6 delay (even ignoring the nand cost to invert the save enable, since that's not a per-bit cost), which added to the 2 for the SR and 2 for the output gives 10.

I thought one could do 41/8 by using the "forbidden" combination S=1 R=1. However, it seems that it's not deterministic which output switches on during the next cycle. Maybe it was deterministic in an older version of the component?

**Comment by MegaIng** [comment]
@bmerry 41/8 is possible. And yes S=1,R=1 is needed, and the behavior is deterministic

**Comment by bmerry** [comment]
> @bmerry 41/8 is possible. And yes S=1,R=1 is needed, and the behavior is deterministic

Ok thanks. For me it's deterministic in the sense that if I replay the simulation I get the same behaviour on the same ticks, but on some ticks it's A that switches on and other ticks it is B.

**Comment by MegaIng** [comment]
Yes, but it's not random at all. The state of the SR latch doesn't change, so if A was on before both were pulled high, A will be on afterwards.

**Comment by bmerry** [comment]
> Yes, but it's not random at all. The state of the SR latch doesn't change, so if A was on before both were pulled high, A will be on afterwards.

Thanks, with that tip I solved it. I'm not sure if it's really a valid solution though: this solution won't actually work as a register, because it will break if you try to save and load on the same tick.

**Comment by MegaIng** [comment]
@bmerry No solution involving SR latches can work the same as the Register component anyway, same way you can't actually build the 1bm

**Comment by bmerry** [comment]
> @bmerry No solution involving SR latches can work the same as the Register component anyway, same way you can't actually build the 1bm

True, and that's something that's bugged me. Is there a reason the input pins on the SR latch aren't treated as being on the falling edge (marked with a *)? The magic feedback loop that makes memory work is inside the SR latch, rather than in the control logic that 1bm wraps around it.

**Comment by altrag** [comment]
Its one of those things that's playing specifically to the game mechanics rather than any real-world counterpart.  There are a few such "problems" within the game, most of which have been confirmed as intentional for whatever reason (to explicitly avoid random behavior, because its easier for the simulation, whatever).  A couple that still don't have a solid answer from Stuffe (and perhaps he hasn't even decided on them yet).

Generally when we refer to "cheated" solutions we mean either:
1. Using components or features that no longer exist in the game (the old FF component and the byte adder without carry being the two most prominent).
2. Solutions that take advantage of a lack of test coverage and would fail if the test coverage matched the problem description better.  (And people still disagree whether this is "cheating" - I personally treat it as such and try to file bug reports when I discover such cases, but others disagree with my opinion here.)

Solutions that target known game mechanics (especially ones that Stuffe has confirmed are intentional design decisions) are typically not considered "cheating" even if they don't entirely match the operation of their real world counterparts - its a game after all, and there's only so much the simulation can do while still remaining performant enough to be fun.  Some deviation from the real world is necessary/expected.  (But if you want to restrict yourself to real-world designs anyway, there's nothing stopping you provided you don't care about competing on the leaderboards.  The game is pretty open-ended like that.)

**Comment by bmerry** [comment]
So to put it another way: should it be considered a lack of test coverage that Load and Save are never set at the same time in Saving Bytes?

**Comment by altrag** [comment]
Nope.  That's one of the ones that's been confirmed as intentional.  It would cause issues with the way the simulation operates (that load/save split) to test that case (for Saving Bytes you could do it using 1BMs, but that just shifts the problem up a level - Saving Gracefully has the same limitation and there is no way to handle that without a change to how the SR latch operates within the simulation, which as far as I know is not something Stuffe wants to do).

**Comment by scottanderson** [comment]
> Is there a reason the input pins on the SR latch aren't treated as being on the falling edge (marked with a *)? The magic feedback loop that makes memory work is inside the SR latch, rather than in the control logic that 1bm wraps around it.

This is the difference between a latch and a flipflop. For now, the game only provides us with one of each type: SR-Latch and D-Flip-Flop (aka 1-Bit Memory).

> So to put it another way: should it be considered a lack of test coverage that Load and Save are never set at the same time in Saving Bytes?

Flip-Flops in electronics use a clock signal to decide when to write to the Latch within them, but in TC the clocking of the SR latch happens because the game breaks out the load phase and save phase of the circuit into separate sub-ticks, calculating the load phase first, and the save phase second. For the saving* levels, the engine effectively breaks these sub-ticks out into full ticks, giving you the load instruction first and then the save instruction second. When you go to use 1bit memory in your actual circuits, that component follows the previously mentioned two-phase per tick behavior.

This implicit clocking by manipulation of inputs over the course of multiple ticks is what allows you to build a flipflop without a clock input. One way that the game might improve the new player experience would be to render the ticks on saving* levels as "1L, 1S, 2L, 2S, ...", and align inputs to the L/S phases.

**Comment by bmerry** [comment]
Thanks for the explanation. Maybe it would be less confusing if the SR latch component was hidden except in the saving levels. A couple of times I fell into the trap of thinking I could save some gates by replacing a 1bm with an SR latch and simplifying the logic around it, but in fact it seems like a useless component outside of those special levels.

**Comment by bmerry** [comment]
My 60/12 solution to Counter is not valid, exploiting the test coverage. I've filed #198.

**Comment by bmerry** [comment]
> in fact it seems like a useless component outside of those special levels.

I take that back. I think I may have found a use for an SR latch in another level.

**Comment by Stuffe** [comment]
Sorry to be lazy, but in the interest of me doing things fast, would you mind listing the exact scores I should make sure are minimum? For example I see Saving Bytes and I guess 41/8 is the best legit solution? Remember I haven't really had time to play the game competitively yet, so I am a bit out of the loop

**Comment by altrag** [comment]
For the levels I'm currently leading with low or no ties, I can say that at least the following are fully legit solutions:
- Full adder: 6/4
- Adding bytes: 37/18
- Logic engine: 34/6
- Conditions: 8/4
- Calibrating Laser Cannons: 19/4/1
- Storage Cracker: 22/12/9  (Caveat: This is only legit with the broken adversary.  My best general solution is 54/14, though its hard to verify until the adversary is changed.)
- Add 5: 20/6/1
- Robot Racing: 57/10/63

**Comment by MegaIng** [comment]
@Stuffe The recent changes to memory pretty much means that *all* architecture scores are invalid. You should maybe just remove everything < 1000 sum or so (with exception of ADD 5 and other 1 tick levels).

For the once before architectures I will check again and make another list.

**Comment by bmerry** [comment]
For XOR I think the best legitimately possible with the new memory is 61/4/2, although nands/delays can be reduced with more ticks (but that would probably require a second register): 40 nands to hold the initial value, 16 for the XOR, and 5 for one bit of state to track whether we've seen the first input yet.

The current tests don't include a first value of 0, so one can cheat by checking whether the register is non-zero to determine whether we've received the first value, giving 56/4/2.

**Comment by bmerry** [comment]
> For XOR I think the best legitimately possible with the new memory is 61/4/2, although nands/delays can be reduced with more ticks (but that would probably require a second register): 40 nands to hold the initial value, 16 for the XOR, and 5 for one bit of state to track whether we've seen the first input yet.
> 
> The current tests don't include a first value of 0, so one can cheat by checking whether the register is non-zero to determine whether we've received the first value, giving 56/4/2.

This comment pre-dates the delay component that I hear is in the development branch.

**Comment by bmerry** [comment]
With delay components, my XOR in 24/4/2 is a cheat which exploits the first value not being 0 in any of the test cases. 25/4/2 is legit, and I strongly suspect is the lowest possible (unless there is some way to XOR two bytes more efficiently than doing each bit individually). It's 16 nands for the byte XOR and there are 257 possible states (first input not yet loaded, or 256 possible values for the first input) thus requiring 9 delay buffers. The delay could in theory be reduced from 4 to 2 but I think only by adding a lot more delay buffers.

**Comment by bmerry** [comment]
@MegaIng not sure if this is still being maintained or has been superseded by Discourse discussion, but here's my take on what needs to be updated on your list (based just on the top scores). I think it might also be useful to actually list what we believe is the best-known valid solution so that we know when something is new and needs investigation. 

The following now look fine i.e. top score is believed to be legit:
- Adding bytes (37/18)
- Saving bytes (33/4), unless Stuffe decides that initial state should be tested as 0
- Counter (33/6)
- Signed negator (14/4)
- Arithmetic engine (74/24 is mine and I believe is legit)
- Equality (17/6)
- Unsigned less (19/6)
- Signed less (19/6)
- Shift (23/6)
- Product of Nibbles (currently 54/18, but lower scores are probably possible, and @danielrab is working on a 65/6 or better); there are a bunch of 77/20 solutions which were set artificially by @Stuffe
- Delicious order (hard to tell, but I see no reason to disbelieve any of the scores)
- Robot racing (28/4/63, but slightly lower scores may be possible)

The following have legit top scores, but some solutions with too few ticks which need to be adjusted:
- Add 5 (16/6/1)
- Calibrating laser cannons (19/4/1)
- Planet Names (1/0/33)
- Dancing Machine (21/4/18)

The following now have cheese (scores in brackets are valid):
- Bit inverter (2/4)
- Instruction decoder (5/4)
- RAM: not sure what the top solution has done, but 128 nand isn't enough to store the necessary state, whether in a RAM or in delay buffers; not sure what the best possible is)
- Tower of radioactive alloy (scores with tick counts of 29 and 32 are impossible)
- Water world (169/16/34, and I can probably reduce it a little)

**Comment by Stuffe** [comment]
I put in a bunch of effort to fix this up and I think it has been. Open new issues if not

**Comment by bmerry** [comment]
I haven't cross-checked against the list in this issue, but there is still plenty of known cheese on the leaderboard at turingcomplete.live e.g.
- Bit Inverter (2/2 for what is an XOR)
- Little Box (the 136/8 that doesn't fit in the box)
- Masking time (0 ticks)
- Storage cracker (exploiting the adversarial test case)
- Unsigned less (18/6 which I think is test case abuse)
- XOR (first place has 0 ticks, next two have 24/4 which I think exploited non-zero inputs)
- Divide (0-tick solutions)
- AI showdown (0-tick solutions)
- Waterworld (64/40/17 is abuse of randomly-generated tests: just outputs a fixed value)

As you say it'll all get swept away, but it might matter to people for the badge.
