### ISSUE TITLE
[Bug]: Should nand/delay for RAM be scaled up?

### ISSUE THREAD

**Issue by bmerry** [Turing-Complete-Game/Suggestions-and-Issues#197]
### What happened?

When I create a 256-byte RAM, the nand and delay shown are those from the Little Box level. It ends up with fewer than 1 nand per byte, which is impossible. While the gate counts are somewhat arbitrary (particularly because of free ORs), it's nice (and educational) to get a very rough idea of how your simulated computer compares to actual chips.

I'm not sure what the best solution is. One option would to be to assign it a fixed nand/delay score independent of Little Box. If you want to make optimisation on Little Box count for something, one could multiply the nand count by 64 (since there are 64x as many bytes). That would be an over-estimate, since some of the gates wouldn't need to be replicated. A lower bound would probably be to add the cost of 252 registers + 6 (to decode the other 6 address bits) + 252 * 2 (a nand for the load and for the save pin on each new byte).

To be sure, this is a pretty low priority issue. Just pointing it out in case it's interesting.

### Version

Latest

### Operating System

Ubuntu 20.04

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
The current idea is that the RAM component shouldn't be useless, and more importantly that people going for high scores shouldn't be forced to manually build RAM components of 32 bytes or something like that. While yes, it not scaling up at all is unrealistic, even now it is a "problem" that people are unpacking the RAM when they need just a few bytes of memory (e.g. Stack).

**Comment by bmerry** [comment]
It's a fair point, and feel free to close the ticket.

One idea I had is that maybe the programming levels should prevent components like RAM and the program from being deleted? Then even if they use a lot of gates, they would be effectively free since it's a sunk cost. And once you have a programming component there may be more incentive to actually build a programmable architecture instead of implementing the solution in hardware.

**Comment by zamadatix** [comment]
Manually unpacking to have 3, 5, 17, e.g. bytes is not a fun part of the ground up puzzle experience of the game but at the same time suddenly having 256 register's worth of ability for the price of 4 (and change) as a workaround ruins a lot of the ground up puzzle experience just as well.

Somewhere in the middle... what if the 256 byte RAM block had a pencil button like the program block that let you set the number of bytes to the maximum of 256. This would solve the problem of recreating the same memory design many times for optimization needs but allow the score to be (somewhat) reasonably calculated as `bytes / 4 * littleBoxScore` instead of assuming the cost of 4 bytes even if you use all 256. This becomes even stronger with the 512k of 64 byte RAM where at the moment you can get pretty much all the memory you'll ever need for anything in the game less NAND score than the CPU may take.

Straying a bit far from the original topic but a similar concept could be extended to the programming block which currently uses the same numbers from the "Little Box" level. In this case it could be automatically based on `lastNonZeroByteIndex / 4 * littleBoxScore` instead of needing to be configured by the user.
