### ISSUE TITLE
[Request]: Automatic nesting level for custom components

### ISSUE THREAD

**Issue by scottanderson** [Turing-Complete-Game/Suggestions-and-Issues#22]
### Request?

Compute nesting levels automatically, only inform the player about this if they hit the nesting limit.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
I was considering doing this in the initial implementation but decided to go with explicit management instead. I am afraid making it automatic will not force players to understand and so we will get frequent complaints / bug reports about it. I’ll leave this open if anyone wants to comment since I am not completely convinced either way

**Comment by Stuffe** [comment]
closing for now
