### ISSUE TITLE
[Request]: Bit Switch Clarity

### ISSUE THREAD

**Issue by alexarze** [Turing-Complete-Game/Suggestions-and-Issues#272]
### Request?

This first came up while I was looking for ways to optimize my solution to `Little Box`. I don’t believe there is any direct information alluding to the fact that a `byte switch` can be used for 1-bit buses (aka, wires), but they certainly can be.

I think that either it needs to be made more clear that a single bit can be used with a switch, OR more simply **just make a 1-bit switch**. That would also make the UI more sensical, where inputting a solo wire into a switch results in a bus output, which is confusing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pr0metheus42** [comment]
a 1-bit switch is literally just an and gate, and making the output wire of a component depend on what type the input wire is could be even more confusing to players

**Comment by alexarze** [comment]
Right - however, as in a level like `Little Box` where space means everything, having that many AND gates is infeasible. It just feels like there’s little advantage to using an AND gate over a switch, but then you end up with a bus instead.

Ultimately that’s just my opinion, though. Maybe reducing the overall size of gates once you achieve a certain level?

**Comment by MegaIng** [comment]
The reason to use AND gates instead of Switches is because of score, which you probably didn't unlock till now.

Also, in Little Box the space is supposed to be a challenge. This is completely irrelevant in all later levels, where you have enough space to just use AND gates. Therefore it doesn't really make sense to reduce the size if that is supposed to be the challenge.
