### ISSUE TITLE
[Bug]: Game uses `XDG_CONFIG_HOME` or `XDG_DATA_HOME` to set game saves directory

### ISSUE THREAD

**Issue by cpkio** [Turing-Complete-Game/Suggestions-and-Issues#302]
### What happened?

I got the game installed on Windows 10 x64 from Steam and found out it saves games to `C:/NvimLua/Godot/app_userdata/Turing Complete` (which is my Neovim portable installation). It seems the game takes folder location from `XDG_CONFIG_HOME` or `XDG_DATA_HOME` environment variables which both point to `C:\NvimLua` in my system, and not `APPDATA`.

Additionally, the saved game location is unchangeable, which in conjunction with former is unfortunate.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This is the expected behavior when `XDG_DATA_HOME` is defined. That environment variables tells all programs where user data should go. This is builtin into godot since it follows the corresponding standard: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html , https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html .
