### ISSUE TITLE
[Request]:  When completing a level, the save of that level is seperate.

### ISSUE THREAD

**Issue by WarlockD** [Turing-Complete-Game/Suggestions-and-Issues#311]
### Request?

I made a mistake and screwed up my cpu architecture before the mase and when I went back I found that it it didn't have any of the old stuff during the campaign.  While its NOT a huage deal, it messes up trying to go back to previously done maps to figure out how they worked.  Is it posable to have a button to switch between what the user used to do that map and the current "cpu"?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Pr0metheus42** [comment]
this is fully intentional since the levels are supposed to test if your cpu has these capabilities. if they were separate people would break something and not realise what is broken causing more confusion. there are saved versions of your best solution so restoring that should be possible. but in general architecture levels should share their architecture.

**Comment by Stuffe** [comment]
Yes this is indeed very much per design. I think it becomes clear a bit later why this is so powerful

**Comment by WarlockD** [comment]
I think its because I am so used to git.  I keep wanting to save my itlterations:P
