### ISSUE TITLE
[Request]: Histograms of user scores

### ISSUE THREAD

**Issue by jlumpe** [Turing-Complete-Game/Suggestions-and-Issues#399]
### Request?

The game Shenzhen IO (which has a lot of similarity to Turing Complete) and several other games by the same publisher feature a histogram of user scores that you can compare yours to when you complete a puzzle. I think this would be a great addition to the game, currently it's hard to know if it's possible to do much better on a given puzzle.

Example:
![example](https://www.gamingnexus.com/Images/Article/udxexl5423/5.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SleepProgger** [comment]
Just fyi: in the meanwhile there is this fan-project: 
https://turingcomplete.live/#any_doubles

Having something like that integrated in the game would be awesome tho.

**Comment by Stuffe** [comment]
I don't think I will be adding this. Many of the levels have extremely hard to reach optimal solutions, even the early game ones. A lot of players have an expectation of being able to find the best scores and will get frustrated otherwise, but most of the best scores have been found by players sharing information. I think a leaderboard somewhere is fine, but I don't want it too "in your face"
