### ISSUE TITLE
[Bug]: AI Showdown Test Algorithm Randomness

### ISSUE THREAD

**Issue by bombitmanbomb** [Turing-Complete-Game/Suggestions-and-Issues#4]
### What happened?

Level AI Showdown, Hard coding the output 3, 2, 2, 2 has a 1 in 18 chance to pass all 3 tests.

![Screenshot_19](https://user-images.githubusercontent.com/11261721/140780093-87b8a19a-3fdd-4d0e-8bf1-75585edb8781.png)

![Screenshot_20](https://user-images.githubusercontent.com/11261721/140780670-9b852a78-1a5d-4ce1-b3fe-1c6c13ea09f1.png)

### Version

Development

### Operating System

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
I would actually not consider this a bug. The game is very simplicity. The perfect score for this game is very very low anyway. The AI does not have that many option.

But I agree that the AI should be harder, it should be straight up adversarial: Try every possible move if you know that you would lose vs a perfect player. At the moment the AI never chooses 3, meaning that the perfect ASIC can be improved by knowing ever more by abusing that.

**Comment by scottanderson** [comment]
I think the game repeating the same test cases is a bug. The solution is <details><summary>Click to reveal spoiler</summary> a simple 2-bit truth table</details> and the game could do a much better job of checking whether that's what the player's circuit does.

I also believe that the AI never choosing 3 should be patched - ie, at least one test case should include that scenario.

However the level can still be solved completely legit with only <details><summary>Click to reveal spoiler</summary> 2 nand (and it only takes a single not gate right now, due to AI never choosing 3)</details> so this level is definitely not intended to be a big challenge.

**Comment by Stuffe** [comment]
fixed in 0.328
