### ISSUE TITLE
[Bug]: Campaign not proceeding after introduction

### ISSUE THREAD

**Issue by Eylard** [Turing-Complete-Game/Suggestions-and-Issues#447]
### What happened?

Just installed the game after buying and started the campaign. Finished the not gate, in the level tree that pops up everything is red (locked) besides crude awakening. This one is yellow (available) and brings me back to the start of the campaign.

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This will hopefully be fixed soon. For the moment, you can use this `progress.dat` file to mark the levels as complete. Check the options menu for where your save folder is, and replace the `progress.dat` file there with the one from this zip.

[progress.zip](https://github.com/Turing-Complete-Game/Suggestions-and-Issues/files/8733998/progress.zip)

Note: It is normally *not* suggested to share the progress.dat file, since it contains a private token that would allow others to do stuff in your name on the server. I edited my personal token out of the above file, so the game will fill in yours.

**Comment by Eylard** [comment]
Thanks for the quick response.

**Comment by MegaIng** [comment]
This should be fixed
