### ISSUE TITLE
[Bug]: Simulating 1 and 3 bit decoders crashes game

### ISSUE THREAD

**Issue by tali713** [Turing-Complete-Game/Suggestions-and-Issues#98]
### What happened?

**Game Version:** 0.314 Beta
**Description:** Regardless of simplicity of circuit, any circuit using a 1 bit decoders (from the parts bin) crashes to desktop.

### Version

Latest

### Operating System

Linux (Ubuntu 10.04)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tali713** [comment]
Correction: 3-bit decoders are fine.

**Comment by MegaIng** [comment]
https://discord.com/channels/828292123936948244/828292126328487998/912311659396202526

- Doesn't crash on Windows with build 0.314
- Crashes on Linux with build 0.314, didn't crash on 0.303
- stderr on Linux: 

```
fatal.nim(49)            sysFatal
Error: unhandled exception: types.nim(919, 14) `i == 0`  [AssertionDefect]
```

**Comment by Stuffe** [comment]
That file has something to with the scripting language that runs the levels. Please upload the save here https://turingcomplete.game/report_bug and I should be able to fix it fast if it is reproducible.

I am closing this since the title is misleading, we don't know much more about this than "a bug exists"

**Comment by tali713** [comment]
Submitted using form.  Would you like me to reopen the issue with a correct title and more information, or is the form submission sufficient?
